'use client'

import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight, BarChart3, BriefcaseBusiness, CheckCircle2, Database, Download, Github, GraduationCap, Instagram, Linkedin, Mail, Menu, Moon, PanelTop, PieChart, Send, Sparkles, Sun, Terminal, X, Zap } from 'lucide-react'

const nav = ['Home','About','Skills','Projects','Experience','Education','Services','Certifications','Achievements','Testimonials','Contact']
const placeholder = 'Editable placeholder'
const skills = {
  'Data Analysis':['Excel','SQL','Python','Pandas','NumPy'],
  'Data Visualization':['Power BI','Tableau','Matplotlib','Seaborn'],
  'Databases':['MySQL','PostgreSQL','SQL Server'],
  'Data & Analytics':['Data Cleaning','Exploratory Data Analysis','Data Visualization','Statistical Analysis','KPI Analysis','Business Intelligence','Dashboard Development','Data Reporting']
}
const projects = ['Sales Data Analysis','Customer Churn Analysis','E-commerce Analytics Dashboard','Financial Data Analysis','HR Analytics','Marketing Analytics']
const services = [
 ['Data Cleaning','Prepare structured, analysis-ready datasets from raw inputs.',Database],
 ['Exploratory Data Analysis','Find patterns, anomalies and useful questions in datasets.',BarChart3],
 ['Dashboard Development','Build clear KPI and reporting experiences for decision support.',PanelTop],
 ['Business Intelligence','Translate operational data into understandable business views.',PieChart],
 ['Data Visualization','Communicate analytical findings with focused visual storytelling.',Sparkles],
 ['SQL Data Analysis','Query, join and summarize relational data for analysis.',Terminal],
 ['Excel Analysis','Organize, transform and analyze data using spreadsheet workflows.',Zap],
 ['Python Data Analysis','Use Python tooling for repeatable analytical workflows.',BriefcaseBusiness]
]

export default function Page(){
 const [dark,setDark]=useState(true); const [open,setOpen]=useState(false); const [sent,setSent]=useState(false)
 useEffect(()=>{ const saved=localStorage.getItem('theme'); if(saved==='light'){setDark(false);document.documentElement.classList.add('light')} },[])
 const toggleTheme=()=>{ const next=!dark; setDark(next); document.documentElement.classList.toggle('light',!next); localStorage.setItem('theme',next?'dark':'light') }
 return <main className="min-h-screen overflow-x-hidden bg-[#050505] text-white transition-colors duration-300 dark:bg-[#050505] light:bg-slate-50 light:text-slate-900">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-black/70 backdrop-blur-xl light:border-slate-200/70 light:bg-white/80">
   <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8">
    <a href="#home" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet-600 text-sm">RP</span> Rudra Prajapati</a>
    <nav className="hidden items-center gap-5 xl:flex">{nav.map(x=><a key={x} href={'#'+x.toLowerCase()} className="text-xs text-white/65 transition hover:text-white light:text-slate-600 light:hover:text-slate-950">{x}</a>)}</nav>
    <div className="flex items-center gap-2"><button aria-label="Toggle theme" onClick={toggleTheme} className="rounded-lg border border-white/10 p-2 hover:bg-white/5 light:border-slate-200">{dark?<Sun size={16}/>:<Moon size={16}/>}</button><a href="#contact" className="hidden rounded-lg bg-white px-3 py-2 text-xs font-semibold text-black sm:block">Resume</a><button aria-label="Open menu" onClick={()=>setOpen(!open)} className="rounded-lg border border-white/10 p-2 xl:hidden">{open?<X size={17}/>:<Menu size={17}/>}</button></div>
   </div>
   {open&&<div className="border-t border-white/10 bg-black/95 px-5 py-4 xl:hidden light:bg-white">{nav.map(x=><a onClick={()=>setOpen(false)} key={x} href={'#'+x.toLowerCase()} className="block py-2 text-sm text-white/75 light:text-slate-700">{x}</a>)}</div>}
  </header>

  <section id="home" className="grid-bg relative mx-auto flex min-h-screen max-w-7xl items-center px-5 pb-20 pt-28 lg:px-8"><div className="pointer-events-none absolute left-1/2 top-1/4 h-80 w-80 -translate-x-1/2 rounded-full bg-violet-600/10 blur-3xl"/>
   <div className="relative grid w-full items-center gap-14 lg:grid-cols-[1.2fr_.8fr]">
    <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.6}}><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1.5 text-xs text-violet-200"><span className="h-1.5 w-1.5 rounded-full bg-violet-400"/> Data Analyst · {placeholder}</div><p className="mb-3 text-sm uppercase tracking-[.3em] text-white/45 light:text-slate-500">Rudra Prajapati</p><h1 className="max-w-3xl text-5xl font-semibold tracking-[-.04em] sm:text-6xl lg:text-7xl">Turning <span className="text-violet-400">Data</span> Into Meaningful Insights.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/60 light:text-slate-600">I work with data to discover patterns, generate insights, build dashboards, and support data-driven decision making.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#projects" className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold transition hover:bg-violet-500">View My Work <ArrowUpRight size={16}/></a><a href="#contact" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold hover:bg-white/5 light:border-slate-300"><Download size={16}/> Download Resume</a><a href="#contact" className="px-2 py-3 text-sm text-white/60 hover:text-white light:text-slate-600">Let&apos;s Connect →</a></div></motion.div>
    <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.7,delay:.1}} className="card glow rounded-3xl p-4"><div className="rounded-2xl border border-white/10 bg-[#090909] p-5 light:bg-slate-50"><div className="mb-8 flex items-center justify-between"><div><p className="text-xs text-white/40 light:text-slate-500">ANALYTICS PREVIEW</p><p className="mt-1 font-medium">Insight Workspace</p></div><BarChart3 className="text-violet-400"/></div><div className="grid grid-cols-3 gap-3">{['Projects','Tools','Skills'].map((x,i)=><div key={x} className="rounded-xl border border-white/8 bg-white/[.03] p-3 light:border-slate-200 light:bg-white"><p className="text-[10px] uppercase text-white/35 light:text-slate-500">{x}</p><p className="mt-2 text-lg font-semibold">—</p><p className="text-[10px] text-violet-300">{i===0?'editable':i===1?'placeholder':'to be added'}</p></div>)}</div><div className="mt-5 h-44 rounded-xl border border-white/8 p-4 light:border-slate-200"><div className="flex h-full items-end gap-2">{[35,55,42,70,58,82,66,90,74,86,61,78].map((h,i)=><div key={i} className="flex-1 rounded-t bg-violet-500/50" style={{height:h+'%'}}/>)}</div></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs text-white/45 light:text-slate-500"><span>Visual motif only</span><span className="text-right">No real data represented</span></div></div></div>
   </div>
  </section>

  <Section id="about" eyebrow="01 / PROFILE" title="Analytical thinking, made visible."><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="card rounded-2xl p-7"><p className="max-w-3xl text-lg leading-8 text-white/70 light:text-slate-600">Rudra&apos;s portfolio is centered on data analysis, business intelligence, data visualization, problem solving, and turning raw data into actionable insights.</p><p className="mt-5 text-sm leading-7 text-white/45 light:text-slate-500">Content marked as a placeholder is intentionally editable until verified personal information is available.</p></div><div className="grid grid-cols-2 gap-3">{['Projects Completed','Technologies','Certifications','Analytical Skills'].map(x=><div className="card rounded-2xl p-5" key={x}><p className="text-xs text-white/40 light:text-slate-500">{x}</p><p className="mt-3 text-2xl font-semibold">—</p><p className="mt-1 text-[11px] text-violet-300">Editable placeholder</p></div>)}</div></div></Section>

  <Section id="skills" eyebrow="02 / TOOLKIT" title="Built around the analyst workflow."><div className="grid gap-4 md:grid-cols-2">{Object.entries(skills).map(([cat,items])=><div key={cat} className="card rounded-2xl p-6"><div className="mb-5 flex items-center justify-between"><h3 className="font-medium">{cat}</h3><Database size={18} className="text-violet-400"/></div><div className="flex flex-wrap gap-2">{items.map(s=><span key={s} className="rounded-lg border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-white/65 transition hover:border-violet-400/40 hover:text-white light:border-slate-200 light:text-slate-600">{s}</span>)}</div><p className="mt-5 text-[11px] text-violet-300">Editable placeholder set — display only after real usage is confirmed.</p></div>)}</div></Section>

  <Section id="projects" eyebrow="03 / WORK" title="Project space, ready for real case studies."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map((p,i)=><motion.article whileHover={{y:-4}} key={p} className="card overflow-hidden rounded-2xl"><div className="grid h-44 place-items-center bg-gradient-to-br from-violet-950/60 to-black"><div className="w-3/4 rounded-xl border border-violet-400/20 bg-black/40 p-4"><div className="flex items-end gap-1.5">{[35,55,40,72,58,82].map((h,j)=><div key={j} className="flex-1 rounded-t bg-violet-500/50" style={{height:h/1.4+'px'}}/>)}</div></div></div><div className="p-6"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-widest text-violet-300">Case study {String(i+1).padStart(2,'0')}</span><ArrowUpRight size={15} className="text-white/40"/></div><h3 className="mt-3 font-medium">{p}</h3><p className="mt-2 text-sm leading-6 text-white/50 light:text-slate-500">Example category only. Replace with a verified project, objective, result, tools, and links.</p><div className="mt-5 flex gap-2"><button className="rounded-lg border border-white/10 px-3 py-2 text-xs light:border-slate-200">GitHub placeholder</button><button className="rounded-lg border border-white/10 px-3 py-2 text-xs light:border-slate-200">Live demo</button></div></div></motion.article>)}</div></Section>

  <Section id="experience" eyebrow="04 / EXPERIENCE" title="Professional timeline"><PlaceholderTimeline icon={BriefcaseBusiness} label="Experience details will appear here once verified."/></Section>
  <Section id="education" eyebrow="05 / EDUCATION" title="Education timeline"><PlaceholderTimeline icon={GraduationCap} label="Degree, institution, duration, and focus areas are editable placeholders."/></Section>

  <Section id="services" eyebrow="06 / CAPABILITIES" title="Data analytics services & capabilities"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(([name,desc,Icon])=><div className="card rounded-2xl p-5 transition hover:-translate-y-1 hover:border-violet-400/30" key={name as string}><Icon className="text-violet-400" size={19}/><h3 className="mt-5 text-sm font-medium">{name as string}</h3><p className="mt-2 text-xs leading-5 text-white/45 light:text-slate-500">{desc as string}</p></div>)}</div><p className="mt-5 text-xs text-white/35 light:text-slate-500">Capabilities, not claims about professional client work, until verified.</p></Section>

  <Section id="certifications" eyebrow="07 / CREDENTIALS" title="Certifications"><PlaceholderGrid label="Certification name · issuer · date · credential ID · credential link"/></Section>
  <Section id="achievements" eyebrow="08 / HIGHLIGHTS" title="Achievements"><PlaceholderGrid label="Competition, hackathon, academic achievement, award, or analytics milestone"/></Section>
  <Section id="testimonials" eyebrow="09 / TRUST" title="Testimonials"><div className="card rounded-2xl p-8 text-center"><p className="text-sm text-white/50 light:text-slate-500">No testimonials provided.</p><p className="mt-2 text-xs text-violet-300">Editable placeholder — add real testimonials only.</p></div></Section>

  <Section id="contact" eyebrow="10 / CONTACT" title="Let&apos;s Connect"><div className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><form className="card rounded-2xl p-6" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="grid gap-4 sm:grid-cols-2"><Field label="Name"/><Field label="Email" type="email"/></div><label className="mt-4 block text-xs text-white/60 light:text-slate-600">Message<textarea required rows={6} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-white/[.03] p-3 text-sm outline-none focus:border-violet-400 light:border-slate-200 light:bg-white" /></label><button className="mt-4 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold hover:bg-violet-500"><Send size={15}/> {sent?'Message queued (frontend demo)':'Send message'}</button></form><div className="space-y-3">{[['Email','mailto:placeholder@example.com',Mail],['GitHub','#',Github],['LinkedIn','#',Linkedin],['Instagram','#',Instagram],['X / Twitter','#',X]].map(([name,href,Icon])=><a href={href as string} key={name as string} className="card flex items-center justify-between rounded-2xl p-5 transition hover:border-violet-400/30"><span className="flex items-center gap-3 text-sm"><Icon size={17} className="text-violet-400"/>{name as string}</span><span className="text-xs text-white/35 light:text-slate-500">Placeholder</span></a>)}</div></div></Section>

  <footer className="border-t border-white/10 px-5 py-8 light:border-slate-200"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs text-white/40 sm:flex-row sm:items-center sm:justify-between light:text-slate-500"><div><span className="font-medium text-white light:text-slate-900">Rudra Prajapati</span> · Data Analyst</div><div>© {new Date().getFullYear()} Rudra Prajapati. All rights reserved.</div></div></footer>
 </main>
}
function Section({id,eyebrow,title,children}:{id:string,eyebrow:string,title:React.ReactNode,children:React.ReactNode}){return <section id={id} className="mx-auto max-w-7xl scroll-mt-20 px-5 py-20 lg:px-8"><div className="mb-8"><p className="text-[10px] font-semibold tracking-[.25em] text-violet-400">{eyebrow}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h2></div>{children}</section>}
function PlaceholderTimeline({icon:Icon,label}:{icon:any,label:string}){return <div className="card rounded-2xl p-8"><div className="flex gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-500/10 text-violet-400"><Icon size={18}/></div><div><h3 className="font-medium">Editable placeholder</h3><p className="mt-2 text-sm leading-6 text-white/50 light:text-slate-500">{label}</p></div></div></div>}
function PlaceholderGrid({label}:{label:string}){return <div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="card rounded-2xl p-6"><div className="h-20 rounded-xl bg-white/[.03] light:bg-slate-100"/><p className="mt-5 text-sm font-medium">Editable placeholder</p><p className="mt-2 text-xs leading-5 text-white/45 light:text-slate-500">{label}</p></div>)}</div>}
function Field({label,type='text'}:{label:string,type?:string}){return <label className="block text-xs text-white/60 light:text-slate-600">{label}<input required type={type} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] p-3 text-sm outline-none focus:border-violet-400 light:border-slate-200 light:bg-white" /></label>}
